### ISSUE TITLE
Collaboration Opportunity

### ISSUE THREAD

**Issue by ross0x01** [fkesheh/gs-pdf-to-mardown#1]
Hi Foad,

I wanted to take a moment to thank you for your extensive contributions to Chatbot-UI. Your work has been incredibly helpful to the community and to me personally. As the creator of HackerGPT, which uses Chatbot-UI as a foundation, I wanted to express my gratitude and ask if you would be open to collaborating on our open-source project (https://github.com/Hacker-GPT).

Your experience with chatbot-UI would be incredibly valuable to our team. Your help would mean a lot to us, and I would be thrilled to have you join us at HackerGPT.

I'm happy to compensate you in any way possible to make your involvement rewarding.

I hope we can work together @fkesheh!

**Comment by fkesheh** [comment]
Hi, ping me on my email foadmk.dev@gmail.com
